version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Docker/login/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./project_app:/project_app
    environment:
      FLASK_ENV: development
      PROJECT_SECRET: $PROJECT_SECRET
  web-files:
    build:
      context: .
      dockerfile: ./Docker/files/Dockerfile
    ports:
      - "8081:81"
    volumes:
      - ./project_app:/project_app
    environment:
      FLASK_ENV: development
      PROJECT_SECRET: $PROJECT_SECRET
  view:
    build:
      context: .
      dockerfile: ./Docker/view/Dockerfile
    ports:
      - "8082:82"
    volumes:
      - ./project_app:/project_app
    environment:
      FLASK_ENV: development
      PROJECT_SECRET: $PROJECT_SECRET
  redis:
    image: "redis:alpine"
